version: '3'

vars:
  NAME: gotify-bark
  TAG: ptah0/{{.NAME}}
  PLATFORM: linux/amd64,linux/arm64

tasks:

  dev:
    cmds:
    - go mod download
    - go build -v -o main
    - cmd: ./main
      ignore_error: true

  run:
    deps:
    - image
    cmds:
    - docker run {{.TAG}}

  deploy:
    deps:
    - image
    cmds:
    - docker run -d --restart unless-stopped --name {{.NAME}} {{.TAG}}

  image:
    cmds:
    - docker buildx build -t {{.TAG}} --load .

  push:
    cmds:
    - docker buildx build -t {{.TAG}} --push --platform {{.PLATFORM}} .

