name: Build gotify-bark Docker Image

on:
  # 当有代码推送到 main 分支时触发构建，其他分支手动构建
  push:
    branches:
      - main
  # 也可以手动触发构建
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到 GitHub Packages
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 获取当前分支名称
      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV

      # 构建 Docker 镜像，并以分支名称打标签，支持多架构
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository }}:${{ env.BRANCH_NAME }} \
            --push \
            .
