name: Build gotify-bark Docker Image

on:
  # 当有代码推送到 main 分支时触发构建
  push:
    branches:
      - main
  # 也可以手动触发构建
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到 Docker Hub（如果需要推送镜像）
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t bnsui/gotify-bark .

      # 推送 Docker 镜像（如果需要）
      - name: Push Docker image
        run: docker push bnsui/gotify-bark
