name: Build gotify-bark Docker Image

on:
  # 当有代码推送到 main 分支时触发构建
  push:
    branches:
      - main
  # 也可以手动触发构建
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到 GitHub Packages
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建 Docker 镜像，并打上合适的标签
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }} .

      # 推送 Docker 镜像到 GitHub Packages
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}
